### ISSUE TITLE
Compile error with GHC7.4

### ISSUE THREAD

**Issue by phadej** [bartavelle/compactmap#1]
```
src/Data/CompactMap.hs:24:5:
    foldr' is not a (visible) method of class `Foldable'

src/Data/CompactMap.hs:27:5:
    foldl' is not a (visible) method of class `Foldable'
```

**Comment by bartavelle** [comment]
It seems that you edited the build constraints in hackage, and I am not seing which version isn't building. I just pushed a new version with proper lower bounds for `base`.

**Comment by phadej** [comment]
For the future, it's not necessary to push new versions if it's only the dependency edit, as the dependencies are (can be) edited (and you can edit dependencies bounds yourself too). 

Especially with incorrect (too wide) bounds, pushing the new version doesn't help

Take for example `pcre-utils`. In complex setup, some other package might have `mtl <2.2` bound, so the solver would find a build plan with older `pcre-utils` - which will fail to compile.

To be clear, I opened the issues to notify that you'd need to correct bounds _or/and_ code. As it's not obvious which GHC versions you want to support (setting up `.travis.yml` with e.g. https://github.com/hvr/multi-ghc-travis, testing GHCs you plan to support would make the fact more obvious)

**Comment by bartavelle** [comment]
Makes sense, thanks!
